# Generated by Django 2.1.7 on 2019-03-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('First', models.CharField(max_length=30)),
                ('Last', models.CharField(max_length=30)),
                ('Phone', models.IntegerField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
