# Generated by Django 2.1.7 on 2019-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_sign_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='First',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='Last',
        ),
        migrations.AddField(
            model_name='sign',
            name='Age',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='Gender',
            field=models.CharField(default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sign',
            name='Phone',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
