# Generated by Django 2.1.7 on 2019-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190319_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='Phone',
            field=models.CharField(default=True, max_length=11, primary_key=True, serialize=False),
        ),
    ]
